/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab7p2_avrilromero;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Valeria Romero
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() throws IOException {
        initComponents();
        leerVehiculos1();
        leerClientes();
        leervendedores();
        leerventas();
        cargarId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_nombrevendedor = new javax.swing.JTextField();
        txt_carrosvendidos = new javax.swing.JTextField();
        txt_dinerogenerado = new javax.swing.JTextField();
        bt_vendedor = new javax.swing.JButton();
        bt_cargar2 = new javax.swing.JButton();
        bt_guardar2 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta_vendedores = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_edadcliente = new javax.swing.JTextField();
        txt_nombrecliente1 = new javax.swing.JTextField();
        txt_profesion = new javax.swing.JTextField();
        txt_cantcarros1 = new javax.swing.JTextField();
        txt_sueldo = new javax.swing.JTextField();
        bt_cliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_clientes = new javax.swing.JTextArea();
        bt_cargar3 = new javax.swing.JButton();
        bt_guardar3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTree();
        jScrollPane5 = new javax.swing.JScrollPane();
        jT2 = new javax.swing.JTree();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_vehiculo = new javax.swing.JTextArea();
        bt_vehiculo = new javax.swing.JButton();
        txt_marca = new javax.swing.JTextField();
        txt_modelo = new javax.swing.JTextField();
        txt_year = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        bt_cargar1 = new javax.swing.JButton();
        bt_guardar1 = new javax.swing.JButton();
        color = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        txt_costoventa = new javax.swing.JTextField();
        cb3 = new javax.swing.JComboBox<>();
        bt_venta = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_venta = new javax.swing.JTextArea();
        bt_cargar4 = new javax.swing.JButton();
        bt_guardar4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        clientes2 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Nombre");

        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Cantidad de carros vendidos");

        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Cantidad de dinero generado");

        txt_nombrevendedor.setBackground(new java.awt.Color(255, 255, 255));

        txt_carrosvendidos.setBackground(new java.awt.Color(255, 255, 255));

        txt_dinerogenerado.setBackground(new java.awt.Color(255, 255, 255));

        bt_vendedor.setBackground(new java.awt.Color(0, 102, 102));
        bt_vendedor.setText("Agregar Vendedor");
        bt_vendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_vendedorMouseClicked(evt);
            }
        });

        bt_cargar2.setBackground(new java.awt.Color(0, 102, 102));
        bt_cargar2.setText("Cargar Archivo");
        bt_cargar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_cargar2MouseClicked(evt);
            }
        });

        bt_guardar2.setBackground(new java.awt.Color(0, 102, 102));
        bt_guardar2.setText("Guardar Archivo");
        bt_guardar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardar2MouseClicked(evt);
            }
        });

        ta_vendedores.setBackground(new java.awt.Color(255, 255, 255));
        ta_vendedores.setColumns(20);
        ta_vendedores.setRows(5);
        jScrollPane6.setViewportView(ta_vendedores);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Eliminar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(txt_nombrevendedor)
                        .addComponent(txt_carrosvendidos)
                        .addComponent(txt_dinerogenerado, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                    .addComponent(bt_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(bt_cargar2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_guardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txt_nombrevendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel7)
                        .addGap(29, 29, 29)
                        .addComponent(txt_carrosvendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel8)
                        .addGap(26, 26, 26)
                        .addComponent(txt_dinerogenerado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(bt_guardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_cargar2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vendedor", jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Nombre");

        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Edad");

        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Profesión");

        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Cantidad de Carros Comprados");

        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Cantidad de Sueldo Disponible");

        txt_edadcliente.setBackground(new java.awt.Color(255, 255, 255));

        txt_nombrecliente1.setBackground(new java.awt.Color(255, 255, 255));

        txt_profesion.setBackground(new java.awt.Color(255, 255, 255));

        txt_cantcarros1.setBackground(new java.awt.Color(255, 255, 255));

        txt_sueldo.setBackground(new java.awt.Color(255, 255, 255));

        bt_cliente.setBackground(new java.awt.Color(0, 102, 102));
        bt_cliente.setText("Agregar Cliente");
        bt_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_clienteMouseClicked(evt);
            }
        });

        ta_clientes.setBackground(new java.awt.Color(255, 255, 255));
        ta_clientes.setColumns(20);
        ta_clientes.setRows(5);
        jScrollPane2.setViewportView(ta_clientes);

        bt_cargar3.setBackground(new java.awt.Color(0, 102, 102));
        bt_cargar3.setText("Cargar Archivo");
        bt_cargar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_cargar3MouseClicked(evt);
            }
        });

        bt_guardar3.setBackground(new java.awt.Color(0, 102, 102));
        bt_guardar3.setText("Guardar Archivo");
        bt_guardar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardar3MouseClicked(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 102, 102));
        jButton4.setText("Eliminar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addComponent(txt_edadcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cantcarros1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_profesion, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(bt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)))))
                .addGap(163, 163, 163)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(bt_cargar3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(bt_guardar3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(267, 267, 267))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(88, 88, 88)
                    .addComponent(txt_nombrecliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(714, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel9)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txt_edadcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txt_profesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txt_cantcarros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cargar3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(bt_guardar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(txt_nombrecliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(431, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Cliente", jPanel4);

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));

        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("Administración");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setText("Actividades");

        jt1.setBackground(new java.awt.Color(255, 255, 255));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Admin");
        jt1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane4.setViewportView(jt1);

        jT2.setBackground(new java.awt.Color(255, 255, 255));
        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Dia");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Venta");
        treeNode1.add(treeNode2);
        jT2.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane5.setViewportView(jT2);

        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setText("Cargar Ventas del dia");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 102, 102));
        jButton8.setText("Cargar Informacion");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(189, 189, 189))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Jtrees", jPanel6);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Marca");

        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Color");

        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Modelo");

        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Año");

        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Precio de Venta");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        ta_vehiculo.setBackground(new java.awt.Color(255, 255, 255));
        ta_vehiculo.setColumns(20);
        ta_vehiculo.setForeground(new java.awt.Color(0, 0, 0));
        ta_vehiculo.setRows(5);
        jScrollPane1.setViewportView(ta_vehiculo);

        bt_vehiculo.setBackground(new java.awt.Color(0, 102, 102));
        bt_vehiculo.setText("Agregar Vehiculo");
        bt_vehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_vehiculoMouseClicked(evt);
            }
        });

        txt_marca.setBackground(new java.awt.Color(255, 255, 255));

        txt_modelo.setBackground(new java.awt.Color(255, 255, 255));

        txt_year.setBackground(new java.awt.Color(255, 255, 255));

        txt_precio.setBackground(new java.awt.Color(255, 255, 255));

        bt_cargar1.setBackground(new java.awt.Color(0, 102, 102));
        bt_cargar1.setText("Cargar Archivo");
        bt_cargar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_cargar1MouseClicked(evt);
            }
        });

        bt_guardar1.setBackground(new java.awt.Color(0, 102, 102));
        bt_guardar1.setText("Guardar Archivo");
        bt_guardar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardar1MouseClicked(evt);
            }
        });

        color.setBackground(new java.awt.Color(255, 255, 255));

        jButton5.setBackground(new java.awt.Color(0, 102, 102));
        jButton5.setText("Eliminar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(color))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_marca))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_modelo))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_year))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_precio, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addGap(149, 149, 149)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_cargar1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(bt_guardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addComponent(bt_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_cargar1)
                            .addComponent(bt_guardar1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vehiculo", jPanel2);

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Vendedor");

        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("Cliente");

        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("Costo");

        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("Carro vendido");

        cb1.setBackground(new java.awt.Color(255, 255, 255));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        txt_costoventa.setBackground(new java.awt.Color(255, 255, 255));

        cb3.setBackground(new java.awt.Color(255, 255, 255));
        cb3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb3ItemStateChanged(evt);
            }
        });

        bt_venta.setBackground(new java.awt.Color(0, 102, 102));
        bt_venta.setText("Agregar Venta");
        bt_venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_ventaMouseClicked(evt);
            }
        });

        ta_venta.setBackground(new java.awt.Color(255, 255, 255));
        ta_venta.setColumns(20);
        ta_venta.setRows(5);
        jScrollPane3.setViewportView(ta_venta);

        bt_cargar4.setBackground(new java.awt.Color(0, 102, 102));
        bt_cargar4.setText("Cargar Archivo");
        bt_cargar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_cargar4MouseClicked(evt);
            }
        });

        bt_guardar4.setBackground(new java.awt.Color(0, 102, 102));
        bt_guardar4.setText("Guardar Archivo");
        bt_guardar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardar4MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setText("Terminar Ventas");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setText("update opciones");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        clientes2.setBackground(new java.awt.Color(255, 255, 255));

        jButton6.setBackground(new java.awt.Color(0, 153, 153));
        jButton6.setText("Limpiar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_costoventa)
                                    .addComponent(cb3, 0, 191, Short.MAX_VALUE)
                                    .addComponent(clientes2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(bt_venta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(bt_cargar4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(bt_guardar4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(230, 230, 230))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(202, 202, 202)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(599, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_guardar4, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(bt_cargar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addGap(52, 52, 52)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(clientes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txt_costoventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addComponent(bt_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(471, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Venta", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_vendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_vendedorMouseClicked
        // TODO add your handling code here:
        String nombre = txt_nombrevendedor.getText();
        int cant_carros = Integer.parseInt(txt_carrosvendidos.getText());
        double dinero = Integer.parseInt(txt_dinerogenerado.getText());
        boolean valid1 = valid(cant_carros);
        boolean valid2 = valid2(dinero);
        while (valid1 == false) {
            txt_carrosvendidos.setText("");
            cant_carros = Integer.parseInt(txt_carrosvendidos.getText());
            valid1 = valid(cant_carros);
        }
        while (valid2 == false) {
            txt_dinerogenerado.setText("");
            dinero = Double.parseDouble(txt_dinerogenerado.getText());
            valid2 = valid2(dinero);
        }
        // public Vendedor(String nombre, int cant_carros, double dinero)

        File archivo;
        FileWriter fw = null;
        BufferedWriter bw = null;

        try {
            archivo = new File("./Vendedores.txt");
            fw = new FileWriter(archivo, true);
            bw = new BufferedWriter(fw);

            String x = "[";
            x += "\n";
            x += "\t";
            x += nombre;
            x += ",";
            x += "\n";
            x += "\t";
            x += txt_carrosvendidos.getText();
            x += ",";
            x += "\n";
            x += "\t";
            x += txt_dinerogenerado.getText();
            x += ",";
            x += "\n";
            x += "]";
            x += ";";
            bw.write(x);
            bw.newLine();
            bw.flush();
            JOptionPane.showMessageDialog(this,
                    "Agregado exitosamente");
            Vendedor v = new Vendedor(nombre, cant_carros, dinero);
            vendedores.add(v);
            txt_nombrevendedor.setText("");
            txt_carrosvendidos.setText("");
            txt_dinerogenerado.setText("");

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_bt_vendedorMouseClicked

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb1ActionPerformed

    private void bt_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_clienteMouseClicked
        // TODO add your handling code here:
        //  public Cliente(String nombre, int edad, String profesion, int cant_carros, double sueldo) {
        String nombre = txt_nombrecliente1.getText();
        int edad = Integer.parseInt(txt_edadcliente.getText());
        String profesion = txt_profesion.getText();
        int cant_carros = Integer.parseInt(txt_cantcarros1.getText());
        double sueldo = Double.parseDouble(txt_sueldo.getText());
        boolean valid1 = valid(cant_carros);
        boolean valid2 = valid2(sueldo);
        while (valid1 == false) {
            txt_cantcarros1.setText("");
            cant_carros = Integer.parseInt(txt_cantcarros1.getText());
            valid1 = valid(cant_carros);
        }
        while (valid2 == false) {
            txt_sueldo.setText("");
            sueldo = Double.parseDouble(txt_sueldo.getText());
            valid2 = valid2(sueldo);
        }

        File archivo;
        FileWriter fw = null;
        BufferedWriter bw = null;

        try {
            archivo = new File("./Clientes.txt");
            fw = new FileWriter(archivo, true);
            bw = new BufferedWriter(fw);

            String x = "[";
            x += "\n";
            x += "\t";
            x += nombre;
            x += ",";
            x += "\n";
            x += "\t";
            x += txt_edadcliente.getText();
            x += ",";
            x += "\n";
            x += "\t";
            x += txt_profesion.getText();
            x += ",";
            x += "\n";
            x += "\t";
            x += txt_cantcarros1.getText();
            x += ",";
            x += "\n";
            x += "\t";
            x += txt_sueldo.getText();
            x += ",";
            x += "\n";
            x += "]";
            x += ";";
            bw.write(x);
            bw.newLine();
            bw.flush();
            Cliente c = new Cliente(nombre, edad, profesion, cant_carros, sueldo);
            clientes.add(c);
            JOptionPane.showMessageDialog(this,
                    "Agregado exitosamente");
            txt_nombrecliente1.setText("");
            txt_cantcarros1.setText("");
            txt_profesion.setText("");
            txt_sueldo.setText("");
            txt_edadcliente.setText("");

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_bt_clienteMouseClicked

    private void bt_vehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_vehiculoMouseClicked
        // TODO add your handling code here:
        String id1 = generarId();
        while (verifyId(id, id1) == false) {
            id1 = generarId();
            verifyId(id, id1);
        }
        id.add(id1);
        String marca = txt_marca.getText();
        String color1 = color.getText();
        String modelo = txt_modelo.getText();
        int anio = Integer.parseInt(txt_year.getText());
        double precio = Double.parseDouble(txt_precio.getText());
        boolean valid1 = valid(anio);
        boolean valid2 = valid2(precio);
        while (valid1 == false) {
            txt_year.setText("");
            anio = Integer.parseInt(txt_year.getText());
            valid1 = valid(anio);
        }
        while (valid2 == false) {
            txt_precio.setText("");
            precio = Double.parseDouble(txt_precio.getText());
            valid2 = valid2(precio);
        }
        File archivo;
        FileWriter fw = null;
        BufferedWriter bw = null;

        try {
            archivo = new File("./Vehiculos.txt");
            fw = new FileWriter(archivo, true);
            bw = new BufferedWriter(fw);

            String x = "[";
            x += "\n";
            x += "\t";
            x += marca;
            x += ",";
            x += "\n";
            x += "\t";
            x += modelo;
            x += ",";
            x += "\n";
            x += "\t";
            x += color1;
            x += ",";
            x += "\n";
            x += "\t";
            x += txt_year.getText();
            x += ",";
            x += "\n";
            x += "\t";
            x += txt_precio.getText();
            x += ",";
            x += "\n";
            x += "\t";
            x += id1;
            x += ",";
            x += "\n";
            x += "]";
            x += ";";
            bw.write(x);
            bw.newLine();
            bw.flush();
            JOptionPane.showMessageDialog(this,
                    "Agregado exitosamente");
            Vehiculo v = new Vehiculo(marca, color1, modelo, anio, precio, id1);
            vehiculos.add(v);
            txt_marca.setText("");
            txt_modelo.setText("");
            txt_precio.setText("");
            txt_cantcarros1.setText("");
            color.setText("");
            txt_year.setText("");

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_bt_vehiculoMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        DefaultComboBoxModel cb = (DefaultComboBoxModel) cb3.getModel();
        cb.removeAllElements();
        for (Vehiculo x : vehiculos) {
            cb.addElement(x);
        }
        cb3.setModel(cb);
        DefaultComboBoxModel cb2 = (DefaultComboBoxModel) cb1.getModel();

        cb2.removeAllElements();
        for (Vendedor x : vendedores) {
            cb2.addElement(x);
        }
        cb1.setModel(cb2);

        DefaultComboBoxModel cb4 = (DefaultComboBoxModel) clientes2.getModel();
        cb4.removeAllElements();
        for (Cliente x : clientes) {

            cb4.addElement(x);
        }
        clientes2.setModel(cb4);

    }//GEN-LAST:event_jButton3MouseClicked

    private void bt_cargar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cargar2MouseClicked
        // TODO add your handling code here:
        File x = new File("./Vendedores.txt");
        FileReader fr = null;
        BufferedReader br = null;
        try {
            String line = "";
            ArrayList<String> datos = new ArrayList();
            fr = new FileReader(x);
            br = new BufferedReader(fr);//todo lo que esta en el archivo esta en la ram

            String linea1;
            ta_vendedores.setText("");
            while ((linea1 = br.readLine()) != null) {
                ta_vendedores.append(linea1);//lo que se va leyendo se va agregando al text area
                ta_vendedores.append("\n");
            }

        } catch (IOException e) {
            e.printStackTrace();
        }

        try {
            br.close();
            fr.close();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_bt_cargar2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        ta_vendedores.setText("");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        ta_clientes.setText("");
    }//GEN-LAST:event_jButton4MouseClicked

    private void bt_cargar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cargar3MouseClicked
        // TODO add your handling code here:
        File x = new File("./Clientes.txt");
        FileReader fr = null;
        BufferedReader br = null;
        try {
            String line = "";
            ArrayList<String> datos = new ArrayList();
            fr = new FileReader(x);
            br = new BufferedReader(fr);//todo lo que esta en el archivo esta en la ram

            String linea1;
            ta_clientes.setText("");
            while ((linea1 = br.readLine()) != null) {
                ta_clientes.append(linea1);//lo que se va leyendo se va agregando al text area
                ta_clientes.append("\n");
            }

        } catch (IOException e) {
            e.printStackTrace();
        }

        try {
            br.close();
            fr.close();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_cargar3MouseClicked

    private void bt_cargar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cargar1MouseClicked
        // TODO add your handling code here:
        File x = new File("./Vehiculos.txt");
        FileReader fr = null;
        BufferedReader br = null;
        try {
            String line = "";
            ArrayList<String> datos = new ArrayList();
            fr = new FileReader(x);
            br = new BufferedReader(fr);//todo lo que esta en el archivo esta en la ram

            String linea1;
            ta_vehiculo.setText("");
            while ((linea1 = br.readLine()) != null) {
                ta_vehiculo.append(linea1);//lo que se va leyendo se va agregando al text area
                ta_vehiculo.append("\n");
            }

        } catch (IOException e) {
            e.printStackTrace();
        }

        try {
            br.close();
            fr.close();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_bt_cargar1MouseClicked

    private void bt_guardar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardar2MouseClicked
        // TODO add your handling code here:

        FileWriter fw = null;
        BufferedWriter bw = null;

        try {
            File fichero = new File("./Vendedores.txt");
            fw = new FileWriter(fichero);
            bw = new BufferedWriter(fw);
            bw.write(ta_vendedores.getText());//le añade al buffered writer el texto del text area ta_1
            ta_vendedores.setText("");
            bw.flush();
            JOptionPane.showMessageDialog(this,
                    "Archivo guardado exitosamente");

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_bt_guardar2MouseClicked

    private void bt_ventaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ventaMouseClicked
        // TODO add your handling code here:
        DefaultComboBoxModel cb = (DefaultComboBoxModel) cb3.getModel();
        DefaultComboBoxModel cbb = (DefaultComboBoxModel) cb1.getModel();
        DefaultComboBoxModel cbbb = (DefaultComboBoxModel) clientes2.getModel();
        int s1 = cb1.getSelectedIndex();
        int s2 = clientes2.getSelectedIndex();
        String nombre1 = ((Vendedor) cbb.getElementAt(s1)).getNombre();
        String nombre2 = ((Cliente) cbbb.getElementAt(s2)).getNombre();
        int seleccion = cb3.getSelectedIndex();
        Vehiculo c = (Vehiculo) cb.getElementAt(seleccion);
        double precio = c.getPrecio();
        txt_costoventa.setText(String.valueOf(precio));
        Random r = new Random();
        int idventa = r.nextInt(1, 25000);
        String idventa1 = String.valueOf(idventa);
        File archivo;
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            archivo = new File("./Ventas.txt");
            fw = new FileWriter(archivo, true);
            bw = new BufferedWriter(fw);
            String x = "[";
            x += "\n";
            x += "\t";
            x += idventa1;
            x += ",";
            x += "\n";
            x += "\t";
            x += nombre1;
            x += ",";
            x += "\n";
            x += "\t";
            x += nombre2;
            x += ",";
            x += "\n";
            x += "\t";
            x += txt_costoventa.getText();
            x += ",";
            x += "\n";
            x += "\t";
            x += c.getModelo();
            x += ",";
            x += "\n";
            x += "\t";
            x += c.getId();
            x += ",";
            x += "\n";
            x += "]";
            x += ";";
            bw.write(x);
            bw.newLine();
            bw.flush();
            JOptionPane.showMessageDialog(this,
                    "Agregado exitosamente");
            txt_costoventa.setText("");
            //   public Venta(String vendedor, String cliente, double transaccion, String carro,String Id) 
            Venta venta = new Venta(nombre1, nombre2, precio, c.getModelo(), c.getId(), idventa1);
            ventasdia.add(venta);
            ventas.add(venta);
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_bt_ventaMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        ta_vehiculo.setText("");
    }//GEN-LAST:event_jButton5MouseClicked

    private void bt_guardar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardar1MouseClicked
        // TODO add your handling code here:

        FileWriter fw = null;
        BufferedWriter bw = null;

        try {
            File fichero = new File("./Vehiculos.txt");
            fw = new FileWriter(fichero);
            bw = new BufferedWriter(fw);
            bw.write(ta_vendedores.getText());//le añade al buffered writer el texto del text area ta_1
            ta_vendedores.setText("");
            bw.flush();
            JOptionPane.showMessageDialog(this,
                    "Archivo guardado exitosamente");

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_bt_guardar1MouseClicked

    private void bt_guardar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardar3MouseClicked
        // TODO add your handling code here:

        FileWriter fw = null;
        BufferedWriter bw = null;

        try {
            File fichero = new File("./Clientes.txt");
            fw = new FileWriter(fichero);
            bw = new BufferedWriter(fw);
            bw.write(ta_vendedores.getText());//le añade al buffered writer el texto del text area ta_1
            ta_vendedores.setText("");
            bw.flush();
            JOptionPane.showMessageDialog(this,
                    "Archivo guardado exitosamente");

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_bt_guardar3MouseClicked

    private void bt_cargar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cargar4MouseClicked
        // TODO add your handling code here:
        File x = new File("./Ventas.txt");
        FileReader fr = null;
        BufferedReader br = null;
        try {
            String line = "";
            ArrayList<String> datos = new ArrayList();
            fr = new FileReader(x);
            br = new BufferedReader(fr);//todo lo que esta en el archivo esta en la ram

            String linea1;
            ta_venta.setText("");
            while ((linea1 = br.readLine()) != null) {
                ta_venta.append(linea1);//lo que se va leyendo se va agregando al text area
                ta_venta.append("\n");
            }

        } catch (IOException e) {
            e.printStackTrace();
        }

        try {
            br.close();
            fr.close();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_cargar4MouseClicked

    private void cb3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb3ItemStateChanged
        DefaultComboBoxModel cb = (DefaultComboBoxModel) cb3.getModel();
        try {
            int seleccion = cb3.getSelectedIndex();
            Vehiculo c = (Vehiculo) cb.getElementAt(seleccion);

            double precio = c.getPrecio();
            txt_costoventa.setText(String.valueOf(precio));
        } catch (Exception e) {
        }

    }//GEN-LAST:event_cb3ItemStateChanged

    private void bt_guardar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardar4MouseClicked
        // TODO add your handling code here:
        FileWriter fw = null;
        BufferedWriter bw = null;

        try {
            File fichero = new File("./Ventas.txt");
            fw = new FileWriter(fichero);
            bw = new BufferedWriter(fw);
            bw.write(ta_venta.getText());//le añade al buffered writer el texto del text area ta_1
            ta_venta.setText("");
            bw.flush();
            JOptionPane.showMessageDialog(this,
                    "Archivo guardado exitosamente");

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_bt_guardar4MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showSaveDialog(this);//mostrar el filechooser, en modo save , el valor entero es una constante de las opciones que escogio
        if (seleccion == JFileChooser.APPROVE_OPTION) {//se inicia cuando se da click en el boton guardar
            File fichero;
            fichero = new File(fileChooser.getSelectedFile() + ".txt");
            FileWriter fw = null;
            BufferedWriter bw = null;

            try {
                fw = new FileWriter(fichero);
                bw = new BufferedWriter(fw);
                for (int i = 0; i < ventasdia.size(); i++) {
                    String input = "[";
                    input += "\n";
                    input += "\t";
                    input += ventasdia.get(i).getIdventa();
                    input += ",";
                    input += "\n";
                    input += "\t";
                    input += ventasdia.get(i).getVendedor().toString();
                    input += ",";
                    input += "\n";
                    input += "\t";
                    input += ventasdia.get(i).getCliente().toString();
                    input += ",";
                    input += "\n";
                    input += "\t";
                    input += ventasdia.get(i).getCarro();
                    input += ",";
                    input += "\n";
                    input += "\t";
                    input += ventasdia.get(i).getId();
                    input += ",";
                    input += "\n";
                    input += "\t";
                    input += String.valueOf(ventasdia.get(i).getTransaccion());
                    input += "\n";
                    input += "];";
                    bw.write(input);
                    bw.newLine();
                }
                bw.flush();
                JOptionPane.showMessageDialog(this,
                        "Archivo guardado exitosamente");

            } catch (Exception e) {
                e.printStackTrace();
            }
            try {
                bw.close();
                fw.close();
            } catch (IOException ex) {
            }
        }

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        ta_venta.setText("");
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        DefaultTreeModel modeloARBOL
                = (DefaultTreeModel) jT2.getModel();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) modeloARBOL.getRoot();
        raiz.removeAllChildren();
        for (Venta venta : ventasdia) {
            DefaultMutableTreeNode venta1 = new DefaultMutableTreeNode(venta.getIdventa());
            DefaultMutableTreeNode nombre1 = new DefaultMutableTreeNode(venta.getVendedor());
            DefaultMutableTreeNode nombre2 = new DefaultMutableTreeNode(venta.getCliente());
            DefaultMutableTreeNode carroid = new DefaultMutableTreeNode(venta.getId());
            DefaultMutableTreeNode carro = new DefaultMutableTreeNode(venta.getCarro());
            carroid.add(carro);
            venta1.add(nombre1);
            venta1.add(nombre2);
            venta1.add(carroid);
            raiz.add(venta1);

        }
        modeloARBOL.reload();
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        DefaultTreeModel modeloARBOL
                = (DefaultTreeModel) jt1.getModel();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) modeloARBOL.getRoot();
        raiz.removeAllChildren();
        DefaultMutableTreeNode vendedores1
                = new DefaultMutableTreeNode("Vendedores");
        DefaultMutableTreeNode clientes1
                = new DefaultMutableTreeNode("Clientes");
        DefaultMutableTreeNode carros
                = new DefaultMutableTreeNode("Carros");
        DefaultMutableTreeNode ventas11
                = new DefaultMutableTreeNode("Ventas");
        for (Vehiculo vehiculo : vehiculos) {
             DefaultMutableTreeNode v
                = new DefaultMutableTreeNode(vehiculo.toString());
             carros.add(v);
        }
        for (Vendedor vendedore : vendedores) {
             DefaultMutableTreeNode v
                = new DefaultMutableTreeNode(vendedore.toString());
             vendedores1.add(v);
        }
        for (Cliente cliente : clientes) {
             DefaultMutableTreeNode v
                = new DefaultMutableTreeNode(cliente.toString());
             clientes1.add(v);
        }
        for (Venta venta : ventas) {
             DefaultMutableTreeNode v
                = new DefaultMutableTreeNode(venta.toString());
             ventas11.add(v);
        }
        raiz.add(ventas11);
        raiz.add(vendedores1);
        raiz.add(carros);
        raiz.add(clientes1);
        modeloARBOL.reload();

    }//GEN-LAST:event_jButton8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public static boolean valid(int x) {
        if (x <= 0) {
            return false;
        } else {
            return true;
        }
    }

    public static boolean valid2(double x) {
        if (x <= 0) {
            return false;
        } else {
            return true;
        }
    }

    public void leerVehiculos1() throws FileNotFoundException, IOException {

        File x = new File("./Vehiculos.txt");
        FileReader fr = null;
        BufferedReader br = null;
        try {
            String line = "";
            ArrayList<String> datos = new ArrayList();
            fr = new FileReader(x);
            br = new BufferedReader(fr);//todo lo que esta en el archivo esta en la ram
            String linea;
            while ((linea = br.readLine()) != null) {
                if (!linea.contains(";")) {
                    line += linea;
                } else {
                    line += "\n]";
                    datos.add(line);
                    line = "";

                }

            }
            for (int i = 0; i < datos.size(); i++) {
                String line2 = datos.get(i).toString();
                String[] token = line2.split(",");
                token[0] = token[0].substring(2, token[0].length());
                token[1] = token[1].substring(1, token[1].length());
                token[2] = token[2].substring(1, token[2].length());
                token[3] = token[3].substring(1, token[3].length());
                token[4] = token[4].substring(1, token[4].length());
                token[5] = token[5].substring(1, token[5].length() - 2);
                //public Vehiculo(int id, String Marca, Color color, String modelo, int year, double precio) {
                String marca = token[0];
                String modelo = token[1];
                String color = token[2];
                int year = Integer.parseInt(token[3]);
                double precio = Double.parseDouble(token[4]);
                String id = token[5];

                Vehiculo v = new Vehiculo(marca, color, modelo, year, precio, id);
                vehiculos.add(v);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        br.close();
        fr.close();

    }

    public void leerClientes() throws IOException {
        File x = new File("./Clientes.txt");
        FileReader fr = null;
        BufferedReader br = null;
        try {
            String line = "";
            ArrayList<String> datos = new ArrayList();
            fr = new FileReader(x);
            br = new BufferedReader(fr);//todo lo que esta en el archivo esta en la ram
            String linea;
            while ((linea = br.readLine()) != null) {
                if (!linea.contains(";")) {
                    line += linea;
                } else {
                    line += "\n]";
                    datos.add(line);
                    line = "";

                }

            }

            for (int i = 0; i < datos.size(); i++) {
                String line2 = datos.get(i).toString();
                String[] token = line2.split(",");
                token[0] = token[0].substring(2, token[0].length());
                token[1] = token[1].substring(1, token[1].length());
                token[2] = token[2].substring(1, token[2].length());
                token[3] = token[3].substring(1, token[3].length());
                token[4] = token[4].substring(1, token[4].length() - 2);
                // public Cliente(String nombre, int edad, String profesion, int cant_carros, double sueldo) {
                String nombre = token[0];
                int edad = Integer.parseInt(token[1]);
                String profesion = token[2];
                int cant_carros = Integer.parseInt(token[3]);
                double sueldo = Double.parseDouble(token[4]);
                Cliente c = new Cliente(nombre, edad, profesion, cant_carros, sueldo);
                clientes.add(c);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        br.close();
        fr.close();

    }

    public void leervendedores() throws IOException {
        File x = new File("./Vendedores.txt");
        FileReader fr = null;
        BufferedReader br = null;
        try {
            String line = "";
            ArrayList<String> datos = new ArrayList();
            fr = new FileReader(x);
            br = new BufferedReader(fr);//todo lo que esta en el archivo esta en la ram
            String linea;
            while ((linea = br.readLine()) != null) {
                if (!linea.contains(";")) {
                    line += linea;
                } else {
                    line += "\n]";
                    datos.add(line);
                    line = "";

                }

            }
            for (int i = 0; i < datos.size(); i++) {
                String line2 = datos.get(i).toString();
                String[] token = line2.split(",");
                token[0] = token[0].substring(2, token[0].length());
                token[1] = token[1].substring(1, token[1].length());
                token[2] = token[2].substring(1, token[2].length() - 2);

                //  public Vendedor(String nombre, int cant_carros, double dinero)
                String nombre = token[0];
                int cant_carros = Integer.parseInt(token[1]);
                double sueldo = Double.parseDouble(token[2]);
                Vendedor v = new Vendedor(nombre, cant_carros, sueldo);
                vendedores.add(v);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        br.close();
        fr.close();
    }

    public void leerventas() throws IOException {
        File x = new File("./Ventas.txt");
        FileReader fr = null;
        BufferedReader br = null;
        try {
            String line = "";
            ArrayList<String> datos = new ArrayList();
            fr = new FileReader(x);
            br = new BufferedReader(fr);//todo lo que esta en el archivo esta en la ram
            String linea;
            while ((linea = br.readLine()) != null) {
                if (!linea.contains(";")) {
                    line += linea;
                } else {
                    line += "\n]";
                    datos.add(line);
                    line = "";

                }

            }
            for (int i = 0; i < datos.size(); i++) {
                String line2 = datos.get(i).toString();
                String[] token = line2.split(",");
                token[0] = token[0].substring(2, token[0].length());
                token[1] = token[1].substring(1, token[1].length());
                token[2] = token[2].substring(1, token[2].length());
                token[3] = token[3].substring(1, token[3].length());
                token[4] = token[4].substring(1, token[4].length());
                token[5] = token[5].substring(1, token[5].length() - 2);
                //  public Vendedor(String nombre, int cant_carros, double dinero)
                String nombre = token[1];
                String cliente = token[2];
                double transaccion = Double.parseDouble(token[3]);
                String carro = token[4];
                String id = token[5];
                // public Venta(String vendedor, String cliente, double transaccion, String carro)
                Venta v = new Venta(nombre, cliente, transaccion, carro, id, token[0]);
                ventas.add(v);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        br.close();
        fr.close();
    }

    public void cargarId() throws IOException {
        File x = new File("./Id.txt");
        FileReader fr = null;
        BufferedReader br = null;
        try {
            String line = "";
            ArrayList<String> datos = new ArrayList();
            fr = new FileReader(x);
            br = new BufferedReader(fr);//todo lo que esta en el archivo esta en la ram
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] tokens = linea.split(",");
                id.add(tokens[0]);
            }

        } catch (IOException e) {
            e.printStackTrace();
        }

        br.close();
        fr.close();
    }

    public void escribirId() throws IOException {
        File archivo;
        FileWriter fw = null;
        BufferedWriter bw = null;
        archivo = new File("./Id.txt");
        fw = new FileWriter(archivo, true);
        bw = new BufferedWriter(fw);
        for (String string : id) {
            bw.write(string);
            bw.write(",");
        }
        bw.flush();
    }

    public String generarId() {
        Random r = new Random();
        int x = r.nextInt(1, 10000);
        String y = String.valueOf(x);
        return y;
    }

    public boolean verifyId(ArrayList<String> x, String y) {
        int n = x.size();
        for (int i = 0; i < n - 1; i++) {
            if (x.get(i).equals(y)) {
                return false;
            }
        }
        return true;
    }
    private ArrayList<Vehiculo> vehiculos = new ArrayList();
    private ArrayList<Vendedor> vendedores = new ArrayList();
    private ArrayList<Cliente> clientes = new ArrayList();
    private ArrayList<Venta> ventas = new ArrayList();
    private ArrayList<Venta> ventasdia = new ArrayList();
    private ArrayList<String> id = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cargar1;
    private javax.swing.JButton bt_cargar2;
    private javax.swing.JButton bt_cargar3;
    private javax.swing.JButton bt_cargar4;
    private javax.swing.JButton bt_cliente;
    private javax.swing.JButton bt_guardar1;
    private javax.swing.JButton bt_guardar2;
    private javax.swing.JButton bt_guardar3;
    private javax.swing.JButton bt_guardar4;
    private javax.swing.JButton bt_vehiculo;
    private javax.swing.JButton bt_vendedor;
    private javax.swing.JButton bt_venta;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb3;
    private javax.swing.JComboBox<String> clientes2;
    private javax.swing.JTextField color;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTree jT2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTree jt1;
    private javax.swing.JTextArea ta_clientes;
    private javax.swing.JTextArea ta_vehiculo;
    private javax.swing.JTextArea ta_vendedores;
    private javax.swing.JTextArea ta_venta;
    private javax.swing.JTextField txt_cantcarros1;
    private javax.swing.JTextField txt_carrosvendidos;
    private javax.swing.JTextField txt_costoventa;
    private javax.swing.JTextField txt_dinerogenerado;
    private javax.swing.JTextField txt_edadcliente;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_nombrecliente1;
    private javax.swing.JTextField txt_nombrevendedor;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_profesion;
    private javax.swing.JTextField txt_sueldo;
    private javax.swing.JTextField txt_year;
    // End of variables declaration//GEN-END:variables
}
